spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/igaming
    username: igaminguser
    password: igamingpassword

  jpa:
    hibernate:
      ddl-auto: create  # Optional if you're using Hibernate ORM in reactive
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5433/igaming
    user: igaminguser
    password: igamingpassword


  security:
    user:
      name: myuser
      password: mypassword

#  security:
#    oauth2:
#      client:
#        registration:
#          cognito:
#            client-id: YOUR_CLIENT_ID
#            client-secret: YOUR_CLIENT_SECRET
#            client-authentication-method: client_secret_basic
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid, profile, email
#            authorization-uri: https://YOUR_COGNITO_DOMAIN/oauth2/authorize
#            token-uri: https://YOUR_COGNITO_DOMAIN/oauth2/token
#            user-info-uri: https://YOUR_COGNITO_DOMAIN/oauth2/userInfo
#            jwk-set-uri: https://cognito-idp.YOUR_REGION.amazonaws.com/YOUR_USER_POOL_ID/.well-known/jwks.json
#            client-name: Cognito
#        provider:
#          cognito:
#            issuer-uri: https://cognito-idp.YOUR_REGION.amazonaws.com/YOUR_USER_POOL_ID

logging:
  level:
    root: debug
    sql: debug
#    org.springframework.r2dbc: trace
#    org.springframework.security: trace
#    org.liquibase: trace
